### ISSUE TITLE
add_hdrs and add_srcs aren't copying files in the correct location

### ISSUE THREAD

**Issue by Kernald** [mum4k/platformio_rules#10]
While I'm not exactly sure at which point this changed (it worked fine as of 0e7170eed48fba8c248251c09797a7899b336f2, I suspect f67ac1985fada5e3c0a9802c2e66faa189684a30 to be the culprit), the behaviour of `add_hdrs` and `add_srcs` changed in `platformio_library`: rather than copying those additional files on the same level than the main source and header files, they reproduce the original file structure (e.g. `lib/lib_a/third_party/lib_a/file.h` instead of `lib/lib_a/file.h`).

**Comment by Kernald** [comment]
FWIW: I'm able to add multiple files in `add_hdrs` and `add_srcs` just fine as of 0e7170eed48fba8c248251c09797a7899b336f22. I'm not sure what f67ac1985fada5e3c0a9802c2e66faa189684a30 is really fixing. I reverted this commit and the behaviour is back to what was expected.

**Comment by mum4k** [comment]
Thank you for identifying this. In retrospect I am not sure what that commit is fixing either. This was a result of selectively pulling changes from a fork without fully understanding them.

Do you feel like sending a pull request reverting it?
