### ISSUE TITLE
env_default is deprecated

### ISSUE THREAD

**Issue by Kernald** [mum4k/platformio_rules#19]
Looks like it was renamed in 4.0, and the old name is now deprecated - https://docs.platformio.org/en/latest/migration.html#id1 it should now be `default_envs`. Afaik the only place it's used is the [ini template](https://github.com/mum4k/platformio_rules/blob/master/platformio/platformio.ini.tmpl#L5). I'll send a PR later this week to fix it.

**Comment by mum4k** [comment]
Thank you @Kernald for staying on top of this.
