### ISSUE TITLE
Implement support for Arduino as ISP

### ISSUE THREAD

**Issue by roleroz** [mum4k/platformio_rules#27]
When programming an in-circuit microcontroller you use a programmer, and a very common way to do this is through an Arduino as ISP. This is the standard way to program ATTiny micros, as they normally don't have the USB circuitry around them

PlatformIO supports this mode, but this library doesn't seem to

I'm planning on implementing this change, this issue is for tracking purposes ;)

**Comment by mum4k** [comment]
Thank you for helping to improve this library @roleroz!
